### ISSUE TITLE
Spamming other peoples inboxes will get you nowhere.

### ISSUE THREAD

**Issue by Simonwep** [oceangravity/webskit-gradient-parser#1]
I think I wasn't the only one who received this mail:

> Hi [Probably your first name], my name is Juan Carlos, I just published a npm package to parse CSS gradients https://npmjs.com/package/webskit-gradient-parser maybe it can be useful for your projects, please let me know, thanks! #javascript #css #gradients #npm #webskit
You can test it here: https://codesandbox.io/s/webskit-gradient-parser-bexc5?fontsize=14&hidenavigation=1&theme=dark PR are welcome :) (MIT)

Sending these kind of mails to random people on GitHub won't help your project, this is just plain spamming. Try [/r/javascript](https://www.reddit.com/r/javascript/) if you want feed-back, but sending PM's is not the way to go. Sorry.

**Comment by oceangravity** [comment]
Hey @Simonwep, you are drawing hasty conclusions, I just pretend to help to the community, in fact you are the only one person that I sent the email and a I did because you have a tool called **gpickr** that use gradients, and just thought that maybe you can encounter my tool helpful. So this it's not spamming like you said, I don't pretend get money, fama, or stars, because i don't care, please just ignore my humble email message to you. Sorry if I bothered you, but sometimes we need to understand real purpose until drawing hasty conclusions. Peace.

**Comment by Simonwep** [comment]
In this case I'm sorry for the misunderstanding, there was literally nothing in the mail related to me - this could've been send to anybody and it'd fit; it was _too_ generic. The next time you might mention anything so it's easy to recognize as an mail directed at me :) 

There was even a issue about gradient-parsing ([this one](https://github.com/Simonwep/gpickr/issues/4)) so it'd have been even better if you just add a comment to it instead of sending me an email which is meant to be used for rather private stuff.

I'm sorry again for getting the wrong idea of your intention, I really thought this was some kind of next-level-whatever gathering.
